### ISSUE TITLE
Docs not available

### ISSUE THREAD

**Issue by SOG-web** [Kipras-Zelenkovas/Surreality#1]
the docs link is broken

**Comment by SOG-web** [comment]
Also can this be used a query builder, for example maybe I dont need it to query my db for me, I just want it to build the query and return the string

**Comment by Kipras-Zelenkovas** [comment]
> Also can this be used a query builder, for example maybe I dont need it to query my db for me, I just want it to build the query and return the string

This a good idea, know every function builds a query string and executes it, but I think it could be good idea to return query string as ant opt from function. But there is now one problem, that now everything ( especially select queries with complicated connection ) is not as good as it should to be. Now I am working that all main function could be executed, and will do it in the future to make it more reliable.

**Comment by Kipras-Zelenkovas** [comment]
> the docs link is broken

For docs, there aren't one for now, but will be available in the future. For now you can only use help from comments in the function. Hope it will somehow help it. But in the future there will be docs with examples of usage. Hope you will find somewhat good this orm <3. If you have any other questions, write to me.

**Comment by SOG-web** [comment]
thank so much for the response, I guess I will just move on with my implementation for now
